{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "  from .autonotebook import tqdm as notebook_tqdm\n",
      "2025-02-01 09:36:59,247\tINFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.\n",
      "2025-02-01 09:36:59,527\tINFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.\n",
      "WARNING: All log messages before absl::InitializeLog() is called are written to STDERR\n",
      "E0000 00:00:1738402619.809243   70470 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\n",
      "E0000 00:00:1738402619.812593   70470 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
      "2025-02-01 09:37:05,846\tWARNING deprecation.py:50 -- DeprecationWarning: `rollouts` has been deprecated. Use `AlgorithmConfig.env_runners(..)` instead. This will raise an error in the future!\n",
      "/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/_private/node.py:1362: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2025-02-01_09-37-05_862751_70470/logs/gcs_server.out' mode='a' encoding='utf-8'>\n",
      "  self.start_gcs_server()\n",
      "ResourceWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/_private/node.py:1362: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2025-02-01_09-37-05_862751_70470/logs/gcs_server.err' mode='a' encoding='utf-8'>\n",
      "  self.start_gcs_server()\n",
      "ResourceWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/_private/node.py:1367: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2025-02-01_09-37-05_862751_70470/logs/monitor.out' mode='a' encoding='utf-8'>\n",
      "  self.start_monitor()\n",
      "ResourceWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/_private/node.py:1367: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2025-02-01_09-37-05_862751_70470/logs/monitor.err' mode='a' encoding='utf-8'>\n",
      "  self.start_monitor()\n",
      "ResourceWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/_private/node.py:1378: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2025-02-01_09-37-05_862751_70470/logs/dashboard.err' mode='a' encoding='utf-8'>\n",
      "  self.start_api_server(\n",
      "ResourceWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/_private/node.py:1420: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2025-02-01_09-37-05_862751_70470/logs/raylet.out' mode='a' encoding='utf-8'>\n",
      "  self.start_raylet(plasma_directory, object_store_memory)\n",
      "ResourceWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/_private/node.py:1420: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2025-02-01_09-37-05_862751_70470/logs/raylet.err' mode='a' encoding='utf-8'>\n",
      "  self.start_raylet(plasma_directory, object_store_memory)\n",
      "ResourceWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/_private/node.py:1422: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2025-02-01_09-37-05_862751_70470/logs/log_monitor.err' mode='a' encoding='utf-8'>\n",
      "  self.start_log_monitor()\n",
      "ResourceWarning: Enable tracemalloc to get the object allocation traceback\n",
      "2025-02-01 09:37:06,453\tINFO worker.py:1816 -- Started a local Ray instance.\n",
      "2025-02-01 09:37:06,957\tINFO tune.py:253 -- Initializing Ray automatically. For cluster usage or custom Ray initialization, call `ray.init(...)` before `Tuner(...)`.\n",
      "2025-02-01 09:37:06,959\tINFO tune.py:616 -- [output] This uses the legacy output and progress reporter, as Jupyter notebooks are not supported by the new engine, yet. For more information, please see https://github.com/ray-project/ray/issues/36949\n",
      "/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/tune/tune.py:730: UserWarning: Consider boosting PBT performance by enabling `reuse_actors` as well as implementing `reset_config` for Trainable.\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div class=\"tuneStatus\">\n",
       "  <div style=\"display: flex;flex-direction: row\">\n",
       "    <div style=\"display: flex;flex-direction: column;\">\n",
       "      <h3>Tune Status</h3>\n",
       "      <table>\n",
       "<tbody>\n",
       "<tr><td>Current time:</td><td>2025-02-01 09:37:40</td></tr>\n",
       "<tr><td>Running for: </td><td>00:00:33.87        </td></tr>\n",
       "<tr><td>Memory:      </td><td>10.4/62.8 GiB      </td></tr>\n",
       "</tbody>\n",
       "</table>\n",
       "    </div>\n",
       "    <div class=\"vDivider\"></div>\n",
       "    <div class=\"systemInfo\">\n",
       "      <h3>System Info</h3>\n",
       "      PopulationBasedTraining: 0 checkpoints, 0 perturbs<br>Logical resource usage: 5.0/24 CPUs, 1.0/1 GPUs (0.0/1.0 accelerator_type:G)\n",
       "    </div>\n",
       "    <div class=\"vDivider\"></div>\n",
       "<div class=\"messages\">\n",
       "  <h3>Messages</h3>\n",
       "  \n",
       "  \n",
       "  Number of errored trials: 2<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name                                 </th><th style=\"text-align: right;\">  # failures</th><th>error file                                                                                                                                                                                          </th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>PPO__TODO_MultiAgentBuildingEnv_1a129_00000</td><td style=\"text-align: right;\">           1</td><td>/tmp/ray/session_2025-02-01_09-37-05_862751_70470/artifacts/2025-02-01_09-37-06/PPO_2025-02-01_09-37-05/driver_artifacts/PPO__TODO_MultiAgentBuildingEnv_1a129_00000_0_2025-02-01_09-37-06/error.txt</td></tr>\n",
       "<tr><td>PPO__TODO_MultiAgentBuildingEnv_1a129_00001</td><td style=\"text-align: right;\">           1</td><td>/tmp/ray/session_2025-02-01_09-37-05_862751_70470/artifacts/2025-02-01_09-37-06/PPO_2025-02-01_09-37-05/driver_artifacts/PPO__TODO_MultiAgentBuildingEnv_1a129_00001_1_2025-02-01_09-37-06/error.txt</td></tr>\n",
       "</tbody>\n",
       "</table>\n",
       "</div>\n",
       "<style>\n",
       ".messages {\n",
       "  color: var(--jp-ui-font-color1);\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "  padding-left: 1em;\n",
       "  overflow-y: auto;\n",
       "}\n",
       ".messages h3 {\n",
       "  font-weight: bold;\n",
       "}\n",
       ".vDivider {\n",
       "  border-left-width: var(--jp-border-width);\n",
       "  border-left-color: var(--jp-border-color0);\n",
       "  border-left-style: solid;\n",
       "  margin: 0.5em 1em 0.5em 1em;\n",
       "}\n",
       "</style>\n",
       "\n",
       "  </div>\n",
       "  <div class=\"hDivider\"></div>\n",
       "  <div class=\"trialStatus\">\n",
       "    <h3>Trial Status</h3>\n",
       "    <table>\n",
       "<thead>\n",
       "<tr><th>Trial name                                 </th><th>status  </th><th>loc                  </th><th style=\"text-align: right;\">  num_sgd_iter</th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>PPO__TODO_MultiAgentBuildingEnv_1a129_00002</td><td>PENDING </td><td>                     </td><td style=\"text-align: right;\">            30</td></tr>\n",
       "<tr><td>PPO__TODO_MultiAgentBuildingEnv_1a129_00003</td><td>PENDING </td><td>                     </td><td style=\"text-align: right;\">            20</td></tr>\n",
       "<tr><td>PPO__TODO_MultiAgentBuildingEnv_1a129_00000</td><td>ERROR   </td><td>192.168.200.249:72114</td><td style=\"text-align: right;\">            10</td></tr>\n",
       "<tr><td>PPO__TODO_MultiAgentBuildingEnv_1a129_00001</td><td>ERROR   </td><td>192.168.200.249:72538</td><td style=\"text-align: right;\">            10</td></tr>\n",
       "</tbody>\n",
       "</table>\n",
       "  </div>\n",
       "</div>\n",
       "<style>\n",
       ".tuneStatus {\n",
       "  color: var(--jp-ui-font-color1);\n",
       "}\n",
       ".tuneStatus .systemInfo {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "}\n",
       ".tuneStatus td {\n",
       "  white-space: nowrap;\n",
       "}\n",
       ".tuneStatus .trialStatus {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "}\n",
       ".tuneStatus h3 {\n",
       "  font-weight: bold;\n",
       "}\n",
       ".tuneStatus .hDivider {\n",
       "  border-bottom-width: var(--jp-border-width);\n",
       "  border-bottom-color: var(--jp-border-color0);\n",
       "  border-bottom-style: solid;\n",
       "}\n",
       ".tuneStatus .vDivider {\n",
       "  border-left-width: var(--jp-border-width);\n",
       "  border-left-color: var(--jp-border-color0);\n",
       "  border-left-style: solid;\n",
       "  margin: 0.5em 1em 0.5em 1em;\n",
       "}\n",
       "</style>\n"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[36m(pid=72114)\u001b[0m WARNING: All log messages before absl::InitializeLog() is called are written to STDERR\n",
      "\u001b[36m(pid=72114)\u001b[0m E0000 00:00:1738402627.749482   72114 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\n",
      "\u001b[36m(pid=72114)\u001b[0m E0000 00:00:1738402627.752689   72114 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
      "\u001b[36m(pid=72244)\u001b[0m WARNING: All log messages before absl::InitializeLog() is called are written to STDERR\n",
      "\u001b[36m(pid=72244)\u001b[0m E0000 00:00:1738402633.861790   72244 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\n",
      "\u001b[36m(pid=72244)\u001b[0m E0000 00:00:1738402633.865202   72244 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
      "\u001b[36m(pid=72245)\u001b[0m WARNING: All log messages before absl::InitializeLog() is called are written to STDERR\n",
      "\u001b[36m(pid=72245)\u001b[0m E0000 00:00:1738402633.873010   72245 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\n",
      "\u001b[36m(pid=72245)\u001b[0m E0000 00:00:1738402633.876404   72245 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
      "\u001b[36m(RolloutWorker pid=72244)\u001b[0m /usr/lib/python3.11/tempfile.py:1043: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/.energyplus_output__vzqaqt6'>\n",
      "\u001b[36m(RolloutWorker pid=72244)\u001b[0m   _warnings.warn(warn_message, ResourceWarning)\n",
      "\u001b[36m(pid=72246)\u001b[0m WARNING: All log messages before absl::InitializeLog() is called are written to STDERR\u001b[32m [repeated 2x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#log-deduplication for more options.)\u001b[0m\n",
      "\u001b[36m(pid=72246)\u001b[0m E0000 00:00:1738402633.882605   72246 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=72246)\u001b[0m E0000 00:00:1738402633.885998   72246 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[36m(RolloutWorker pid=72244)\u001b[0m /home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/controllables/energyplus/variables.py:396: RuntimeWarning: OutputVariable(OutputVariable.Ref(type='Zone Mean Air Temperature', key='1FFIRSTFLOORWEST1:OPENOFFICE')) requested while Kernel() is running; It may not be available until the next run. More info: https://energyplus.readthedocs.io/en/latest/datatransfer.html#datatransfer.DataExchange.request_variable\n",
      "\u001b[36m(RolloutWorker pid=72244)\u001b[0m   _warnings_.warn(\n",
      "\u001b[36m(RolloutWorker pid=72244)\u001b[0m /home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/controllables/energyplus/variables.py:396: RuntimeWarning: OutputVariable(OutputVariable.Ref(type='Zone Mean Air Temperature', key='0FGROUNDFLOORWEST:OPENOFFICE')) requested while Kernel() is running; It may not be available until the next run. More info: https://energyplus.readthedocs.io/en/latest/datatransfer.html#datatransfer.DataExchange.request_variable\n",
      "\u001b[36m(RolloutWorker pid=72244)\u001b[0m   _warnings_.warn(\n",
      "\u001b[36m(RolloutWorker pid=72244)\u001b[0m /home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/controllables/energyplus/variables.py:396: RuntimeWarning: OutputVariable(OutputVariable.Ref(type='Zone Mean Air Temperature', key='1FFIRSTFLOOREAST1:OPENOFFICE')) requested while Kernel() is running; It may not be available until the next run. More info: https://energyplus.readthedocs.io/en/latest/datatransfer.html#datatransfer.DataExchange.request_variable\n",
      "\u001b[36m(RolloutWorker pid=72244)\u001b[0m   _warnings_.warn(\n",
      "\u001b[36m(RolloutWorker pid=72244)\u001b[0m /home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/controllables/energyplus/variables.py:396: RuntimeWarning: OutputVariable(OutputVariable.Ref(type='Zone Mean Air Temperature', key='0FGROUNDFLOOREAST:OPENOFFICE')) requested while Kernel() is running; It may not be available until the next run. More info: https://energyplus.readthedocs.io/en/latest/datatransfer.html#datatransfer.DataExchange.request_variable\n",
      "\u001b[36m(RolloutWorker pid=72244)\u001b[0m   _warnings_.warn(\n",
      "\u001b[36m(RolloutWorker pid=72244)\u001b[0m /home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/controllables/energyplus/variables.py:396: RuntimeWarning: OutputVariable(OutputVariable.Ref(type='Zone Mean Air Temperature', key='0FGROUNDFLOOREAST1:OPENOFFICE')) requested while Kernel() is running; It may not be available until the next run. More info: https://energyplus.readthedocs.io/en/latest/datatransfer.html#datatransfer.DataExchange.request_variable\n",
      "\u001b[36m(RolloutWorker pid=72244)\u001b[0m   _warnings_.warn(\n",
      "\u001b[36m(RolloutWorker pid=72244)\u001b[0m /home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/controllables/energyplus/variables.py:396: RuntimeWarning: OutputVariable(OutputVariable.Ref(type='Zone Mean Air Temperature', key='1FFIRSTFLOORWEST:OPENOFFICE')) requested while Kernel() is running; It may not be available until the next run. More info: https://energyplus.readthedocs.io/en/latest/datatransfer.html#datatransfer.DataExchange.request_variable\n",
      "\u001b[36m(RolloutWorker pid=72244)\u001b[0m   _warnings_.warn(\n",
      "\u001b[36m(RolloutWorker pid=72244)\u001b[0m /home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/controllables/energyplus/variables.py:396: RuntimeWarning: OutputVariable(OutputVariable.Ref(type='Zone Mean Air Temperature', key='0FGROUNDFLOORWEST1:OPENOFFICE')) requested while Kernel() is running; It may not be available until the next run. More info: https://energyplus.readthedocs.io/en/latest/datatransfer.html#datatransfer.DataExchange.request_variable\n",
      "\u001b[36m(RolloutWorker pid=72244)\u001b[0m   _warnings_.warn(\n",
      "\u001b[36m(RolloutWorker pid=72244)\u001b[0m /home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/controllables/energyplus/variables.py:396: RuntimeWarning: OutputVariable(OutputVariable.Ref(type='Zone Mean Air Temperature', key='1FFIRSTFLOOREAST:OPENOFFICE')) requested while Kernel() is running; It may not be available until the next run. More info: https://energyplus.readthedocs.io/en/latest/datatransfer.html#datatransfer.DataExchange.request_variable\n",
      "\u001b[36m(RolloutWorker pid=72244)\u001b[0m   _warnings_.warn(\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m Install gputil for GPU system monitoring.\n",
      "2025-02-01 09:37:23,046\tERROR tune_controller.py:1331 -- Trial task failed for trial PPO__TODO_MultiAgentBuildingEnv_1a129_00000\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/air/execution/_internal/event_manager.py\", line 110, in resolve_future\n",
      "    result = ray.get(future)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/_private/auto_init_hook.py\", line 21, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/_private/worker.py\", line 2745, in get\n",
      "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
      "                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/_private/worker.py\", line 901, in get_objects\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(ValueError): \u001b[36mray::PPO.train()\u001b[39m (pid=72114, ip=192.168.200.249, actor_id=c95720c0a365232933aafcd401000000, repr=PPO)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/tune/trainable/trainable.py\", line 331, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/tune/trainable/trainable.py\", line 328, in train\n",
      "    result = self.step()\n",
      "             ^^^^^^^^^^^\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/algorithms/algorithm.py\", line 934, in step\n",
      "    train_results, train_iter_ctx = self._run_one_training_iteration()\n",
      "                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/algorithms/algorithm.py\", line 3528, in _run_one_training_iteration\n",
      "    training_step_results = self.training_step()\n",
      "                            ^^^^^^^^^^^^^^^^^^^^\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/algorithms/ppo/ppo.py\", line 410, in training_step\n",
      "    return self._training_step_old_api_stack()\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/algorithms/ppo/ppo.py\", line 521, in _training_step_old_api_stack\n",
      "    train_batch = synchronous_parallel_sample(\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/execution/rollout_ops.py\", line 100, in synchronous_parallel_sample\n",
      "    sampled_data = worker_set.foreach_worker(\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/env/env_runner_group.py\", line 909, in foreach_worker\n",
      "    FaultTolerantActorManager.handle_remote_call_result_errors(\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/utils/actor_manager.py\", line 638, in handle_remote_call_result_errors\n",
      "    raise result_or_error.get()\n",
      "ray.exceptions.RayTaskError(ValueError): \u001b[36mray::RolloutWorker.apply()\u001b[39m (pid=72244, ip=192.168.200.249, actor_id=37686aa55c9ec4e585702b6901000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7f2ec14071d0>)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/utils/actor_manager.py\", line 194, in apply\n",
      "    raise e\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/utils/actor_manager.py\", line 183, in apply\n",
      "    return func(self, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/execution/rollout_ops.py\", line 102, in <lambda>\n",
      "    (lambda w: w.sample(**random_action_kwargs))\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 680, in sample\n",
      "    batches = [self.input_reader.next()]\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 91, in next\n",
      "    batches = [self.get_data()]\n",
      "               ^^^^^^^^^^^^^^^\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 273, in get_data\n",
      "    item = next(self._env_runner)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 392, in _env_runner\n",
      "    active_envs, to_eval, outputs = _process_observations(\n",
      "                                    ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 627, in _process_observations\n",
      "    prep_obs = preprocessor.transform(raw_obs)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/models/preprocessors.py\", line 324, in transform\n",
      "    self.check_shape(observation)\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/models/preprocessors.py\", line 71, in check_shape\n",
      "    raise ValueError(\n",
      "ValueError: Observation ({'energy': array(-27.596018, dtype=float32), 'power': array(0., dtype=float32), 'comfort': array(-2.596018, dtype=float32)} dtype=None) outside given space (Dict('comfort': Box(-1.0, 1.0, (), float32), 'energy': Box(-1.0, 1.0, (), float32), 'power': Box(-1.0, 1.0, (), float32)))!\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div class=\"trialProgress\">\n",
       "  <h3>Trial Progress</h3>\n",
       "  <table>\n",
       "<thead>\n",
       "<tr><th>Trial name                                 </th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>PPO__TODO_MultiAgentBuildingEnv_1a129_00000</td></tr>\n",
       "<tr><td>PPO__TODO_MultiAgentBuildingEnv_1a129_00001</td></tr>\n",
       "</tbody>\n",
       "</table>\n",
       "</div>\n",
       "<style>\n",
       ".trialProgress {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "  color: var(--jp-ui-font-color1);\n",
       "}\n",
       ".trialProgress h3 {\n",
       "  font-weight: bold;\n",
       "}\n",
       ".trialProgress td {\n",
       "  white-space: nowrap;\n",
       "}\n",
       "</style>\n"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[36m(PPO pid=72114)\u001b[0m 2025-02-01 09:37:23,043\tERROR actor_manager.py:804 -- Ray error (\u001b[36mray::RolloutWorker.apply()\u001b[39m (pid=72244, ip=192.168.200.249, actor_id=37686aa55c9ec4e585702b6901000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7f2ec14071d0>)\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/utils/actor_manager.py\", line 194, in apply\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     raise e\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/utils/actor_manager.py\", line 183, in apply\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     return func(self, *args, **kwargs)\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/execution/rollout_ops.py\", line 102, in <lambda>\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     (lambda w: w.sample(**random_action_kwargs))\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 680, in sample\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     batches = [self.input_reader.next()]\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m                ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 91, in next\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     batches = [self.get_data()]\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m                ^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 273, in get_data\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     item = next(self._env_runner)\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 392, in _env_runner\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     active_envs, to_eval, outputs = _process_observations(\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m                                     ^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 627, in _process_observations\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     prep_obs = preprocessor.transform(raw_obs)\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/models/preprocessors.py\", line 324, in transform\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     self.check_shape(observation)\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/models/preprocessors.py\", line 71, in check_shape\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     raise ValueError(\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m ValueError: Observation ({'energy': array(-27.596018, dtype=float32), 'power': array(0., dtype=float32), 'comfort': array(-2.596018, dtype=float32)} dtype=None) outside given space (Dict('comfort': Box(-1.0, 1.0, (), float32), 'energy': Box(-1.0, 1.0, (), float32), 'power': Box(-1.0, 1.0, (), float32)))!), taking actor 1 out of service.\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m 2025-02-01 09:37:23,043\tERROR actor_manager.py:804 -- Ray error (\u001b[36mray::RolloutWorker.apply()\u001b[39m (pid=72245, ip=192.168.200.249, actor_id=a54243d28882ba7e957b0b6a01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7f229d6059d0>)\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/utils/actor_manager.py\", line 194, in apply\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     raise e\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/utils/actor_manager.py\", line 183, in apply\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     return func(self, *args, **kwargs)\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/execution/rollout_ops.py\", line 102, in <lambda>\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     (lambda w: w.sample(**random_action_kwargs))\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 680, in sample\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     batches = [self.input_reader.next()]\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m                ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 91, in next\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     batches = [self.get_data()]\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m                ^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 273, in get_data\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     item = next(self._env_runner)\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 392, in _env_runner\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     active_envs, to_eval, outputs = _process_observations(\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m                                     ^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 627, in _process_observations\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     prep_obs = preprocessor.transform(raw_obs)\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/models/preprocessors.py\", line 324, in transform\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     self.check_shape(observation)\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/models/preprocessors.py\", line 71, in check_shape\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     raise ValueError(\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m ValueError: Observation ({'power': array(0., dtype=float32), 'energy': array(-27.687977, dtype=float32), 'comfort': array(-2.6879761, dtype=float32)} dtype=None) outside given space (Dict('comfort': Box(-1.0, 1.0, (), float32), 'energy': Box(-1.0, 1.0, (), float32), 'power': Box(-1.0, 1.0, (), float32)))!), taking actor 2 out of service.\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m 2025-02-01 09:37:23,044\tERROR actor_manager.py:804 -- Ray error (\u001b[36mray::RolloutWorker.apply()\u001b[39m (pid=72246, ip=192.168.200.249, actor_id=e766f0acd4e9bb28763545ba01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7f03597aff10>)\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/utils/actor_manager.py\", line 194, in apply\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     raise e\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/utils/actor_manager.py\", line 183, in apply\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     return func(self, *args, **kwargs)\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/execution/rollout_ops.py\", line 102, in <lambda>\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     (lambda w: w.sample(**random_action_kwargs))\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 680, in sample\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     batches = [self.input_reader.next()]\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m                ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 91, in next\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     batches = [self.get_data()]\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m                ^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 273, in get_data\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     item = next(self._env_runner)\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 392, in _env_runner\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     active_envs, to_eval, outputs = _process_observations(\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m                                     ^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 627, in _process_observations\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     prep_obs = preprocessor.transform(raw_obs)\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/models/preprocessors.py\", line 324, in transform\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     self.check_shape(observation)\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/models/preprocessors.py\", line 71, in check_shape\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     raise ValueError(\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m ValueError: Observation ({'energy': array(-27.601759, dtype=float32), 'comfort': array(-2.601759, dtype=float32), 'power': array(0., dtype=float32)} dtype=None) outside given space (Dict('comfort': Box(-1.0, 1.0, (), float32), 'energy': Box(-1.0, 1.0, (), float32), 'power': Box(-1.0, 1.0, (), float32)))!), taking actor 3 out of service.\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m 2025-02-01 09:37:23,044\tERROR actor_manager.py:804 -- Ray error (\u001b[36mray::RolloutWorker.apply()\u001b[39m (pid=72247, ip=192.168.200.249, actor_id=d60698348beae33abb0ce6c401000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7febb7df8ed0>)\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/utils/actor_manager.py\", line 194, in apply\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     raise e\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/utils/actor_manager.py\", line 183, in apply\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     return func(self, *args, **kwargs)\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/execution/rollout_ops.py\", line 102, in <lambda>\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     (lambda w: w.sample(**random_action_kwargs))\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 680, in sample\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     batches = [self.input_reader.next()]\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m                ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 91, in next\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     batches = [self.get_data()]\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m                ^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 273, in get_data\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     item = next(self._env_runner)\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 392, in _env_runner\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     active_envs, to_eval, outputs = _process_observations(\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m                                     ^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 627, in _process_observations\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     prep_obs = preprocessor.transform(raw_obs)\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/models/preprocessors.py\", line 324, in transform\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     self.check_shape(observation)\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/models/preprocessors.py\", line 71, in check_shape\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m     raise ValueError(\n",
      "\u001b[36m(PPO pid=72114)\u001b[0m ValueError: Observation ({'energy': array(-27.51735, dtype=float32), 'comfort': array(-2.5173495, dtype=float32), 'power': array(0., dtype=float32)} dtype=None) outside given space (Dict('comfort': Box(-1.0, 1.0, (), float32), 'energy': Box(-1.0, 1.0, (), float32), 'power': Box(-1.0, 1.0, (), float32)))!), taking actor 4 out of service.\n",
      "\u001b[36m(RolloutWorker pid=72245)\u001b[0m /usr/lib/python3.11/tempfile.py:1043: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/.energyplus_output_y4wfocdx'>\u001b[32m [repeated 7x across cluster]\u001b[0m\n",
      "\u001b[36m(RolloutWorker pid=72245)\u001b[0m   _warnings.warn(warn_message, ResourceWarning)\u001b[32m [repeated 7x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=72607)\u001b[0m WARNING: All log messages before absl::InitializeLog() is called are written to STDERR\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=72607)\u001b[0m E0000 00:00:1738402650.678408   72607 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=72607)\u001b[0m E0000 00:00:1738402650.681783   72607 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[36m(RolloutWorker pid=72245)\u001b[0m /home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/controllables/energyplus/variables.py:396: RuntimeWarning: OutputVariable(OutputVariable.Ref(type='Zone Mean Air Temperature', key='0FGROUNDFLOORWEST:OPENOFFICE')) requested while Kernel() is running; It may not be available until the next run. More info: https://energyplus.readthedocs.io/en/latest/datatransfer.html#datatransfer.DataExchange.request_variable\u001b[32m [repeated 24x across cluster]\u001b[0m\n",
      "\u001b[36m(RolloutWorker pid=72245)\u001b[0m   _warnings_.warn(\u001b[32m [repeated 24x across cluster]\u001b[0m\n",
      "\u001b[36m(RolloutWorker pid=72607)\u001b[0m /usr/lib/python3.11/tempfile.py:1043: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/.energyplus_output_knmhsw30'>\n",
      "\u001b[36m(RolloutWorker pid=72607)\u001b[0m   _warnings.warn(warn_message, ResourceWarning)\n",
      "\u001b[36m(pid=72610)\u001b[0m WARNING: All log messages before absl::InitializeLog() is called are written to STDERR\u001b[32m [repeated 3x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=72610)\u001b[0m E0000 00:00:1738402650.691445   72610 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\u001b[32m [repeated 3x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=72610)\u001b[0m E0000 00:00:1738402650.694766   72610 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\u001b[32m [repeated 3x across cluster]\u001b[0m\n",
      "\u001b[36m(RolloutWorker pid=72609)\u001b[0m /usr/lib/python3.11/tempfile.py:1043: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/.energyplus_output_9f0ej802'>\n",
      "\u001b[36m(RolloutWorker pid=72609)\u001b[0m   _warnings.warn(warn_message, ResourceWarning)\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m Install gputil for GPU system monitoring.\n",
      "\u001b[36m(RolloutWorker pid=72607)\u001b[0m /home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/controllables/energyplus/variables.py:396: RuntimeWarning: OutputVariable(OutputVariable.Ref(type='Zone Mean Air Temperature', key='1FFIRSTFLOORWEST1:OPENOFFICE')) requested while Kernel() is running; It may not be available until the next run. More info: https://energyplus.readthedocs.io/en/latest/datatransfer.html#datatransfer.DataExchange.request_variable\n",
      "\u001b[36m(RolloutWorker pid=72607)\u001b[0m   _warnings_.warn(\n",
      "\u001b[36m(RolloutWorker pid=72607)\u001b[0m /home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/controllables/energyplus/variables.py:396: RuntimeWarning: OutputVariable(OutputVariable.Ref(type='Zone Mean Air Temperature', key='0FGROUNDFLOOREAST1:OPENOFFICE')) requested while Kernel() is running; It may not be available until the next run. More info: https://energyplus.readthedocs.io/en/latest/datatransfer.html#datatransfer.DataExchange.request_variable\n",
      "\u001b[36m(RolloutWorker pid=72607)\u001b[0m   _warnings_.warn(\n",
      "\u001b[36m(RolloutWorker pid=72607)\u001b[0m /home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/controllables/energyplus/variables.py:396: RuntimeWarning: OutputVariable(OutputVariable.Ref(type='Zone Mean Air Temperature', key='0FGROUNDFLOOREAST:OPENOFFICE')) requested while Kernel() is running; It may not be available until the next run. More info: https://energyplus.readthedocs.io/en/latest/datatransfer.html#datatransfer.DataExchange.request_variable\n",
      "\u001b[36m(RolloutWorker pid=72607)\u001b[0m   _warnings_.warn(\n",
      "\u001b[36m(RolloutWorker pid=72607)\u001b[0m /home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/controllables/energyplus/variables.py:396: RuntimeWarning: OutputVariable(OutputVariable.Ref(type='Zone Mean Air Temperature', key='1FFIRSTFLOORWEST:OPENOFFICE')) requested while Kernel() is running; It may not be available until the next run. More info: https://energyplus.readthedocs.io/en/latest/datatransfer.html#datatransfer.DataExchange.request_variable\n",
      "\u001b[36m(RolloutWorker pid=72607)\u001b[0m   _warnings_.warn(\n",
      "\u001b[36m(RolloutWorker pid=72607)\u001b[0m /home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/controllables/energyplus/variables.py:396: RuntimeWarning: OutputVariable(OutputVariable.Ref(type='Zone Mean Air Temperature', key='1FFIRSTFLOOREAST:OPENOFFICE')) requested while Kernel() is running; It may not be available until the next run. More info: https://energyplus.readthedocs.io/en/latest/datatransfer.html#datatransfer.DataExchange.request_variable\n",
      "\u001b[36m(RolloutWorker pid=72607)\u001b[0m   _warnings_.warn(\n",
      "\u001b[36m(RolloutWorker pid=72607)\u001b[0m /home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/controllables/energyplus/variables.py:396: RuntimeWarning: OutputVariable(OutputVariable.Ref(type='Zone Mean Air Temperature', key='0FGROUNDFLOORWEST:OPENOFFICE')) requested while Kernel() is running; It may not be available until the next run. More info: https://energyplus.readthedocs.io/en/latest/datatransfer.html#datatransfer.DataExchange.request_variable\n",
      "\u001b[36m(RolloutWorker pid=72607)\u001b[0m   _warnings_.warn(\n",
      "\u001b[36m(RolloutWorker pid=72607)\u001b[0m /home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/controllables/energyplus/variables.py:396: RuntimeWarning: OutputVariable(OutputVariable.Ref(type='Zone Mean Air Temperature', key='1FFIRSTFLOOREAST1:OPENOFFICE')) requested while Kernel() is running; It may not be available until the next run. More info: https://energyplus.readthedocs.io/en/latest/datatransfer.html#datatransfer.DataExchange.request_variable\n",
      "\u001b[36m(RolloutWorker pid=72607)\u001b[0m   _warnings_.warn(\n",
      "\u001b[36m(RolloutWorker pid=72607)\u001b[0m /home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/controllables/energyplus/variables.py:396: RuntimeWarning: OutputVariable(OutputVariable.Ref(type='Zone Mean Air Temperature', key='0FGROUNDFLOORWEST1:OPENOFFICE')) requested while Kernel() is running; It may not be available until the next run. More info: https://energyplus.readthedocs.io/en/latest/datatransfer.html#datatransfer.DataExchange.request_variable\n",
      "\u001b[36m(RolloutWorker pid=72607)\u001b[0m   _warnings_.warn(\n",
      "2025-02-01 09:37:39,595\tERROR tune_controller.py:1331 -- Trial task failed for trial PPO__TODO_MultiAgentBuildingEnv_1a129_00001\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/air/execution/_internal/event_manager.py\", line 110, in resolve_future\n",
      "    result = ray.get(future)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/_private/auto_init_hook.py\", line 21, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/_private/worker.py\", line 2745, in get\n",
      "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
      "                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/_private/worker.py\", line 901, in get_objects\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(ValueError): \u001b[36mray::PPO.train()\u001b[39m (pid=72538, ip=192.168.200.249, actor_id=c1f6b653592188c88bfe1ef601000000, repr=PPO)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/tune/trainable/trainable.py\", line 331, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/tune/trainable/trainable.py\", line 328, in train\n",
      "    result = self.step()\n",
      "             ^^^^^^^^^^^\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/algorithms/algorithm.py\", line 934, in step\n",
      "    train_results, train_iter_ctx = self._run_one_training_iteration()\n",
      "                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/algorithms/algorithm.py\", line 3528, in _run_one_training_iteration\n",
      "    training_step_results = self.training_step()\n",
      "                            ^^^^^^^^^^^^^^^^^^^^\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/algorithms/ppo/ppo.py\", line 410, in training_step\n",
      "    return self._training_step_old_api_stack()\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/algorithms/ppo/ppo.py\", line 521, in _training_step_old_api_stack\n",
      "    train_batch = synchronous_parallel_sample(\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/execution/rollout_ops.py\", line 100, in synchronous_parallel_sample\n",
      "    sampled_data = worker_set.foreach_worker(\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/env/env_runner_group.py\", line 909, in foreach_worker\n",
      "    FaultTolerantActorManager.handle_remote_call_result_errors(\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/utils/actor_manager.py\", line 638, in handle_remote_call_result_errors\n",
      "    raise result_or_error.get()\n",
      "ray.exceptions.RayTaskError(ValueError): \u001b[36mray::RolloutWorker.apply()\u001b[39m (pid=72607, ip=192.168.200.249, actor_id=61eba594d5a0f1955ab56a9101000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7fa953e26290>)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/utils/actor_manager.py\", line 194, in apply\n",
      "    raise e\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/utils/actor_manager.py\", line 183, in apply\n",
      "    return func(self, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/execution/rollout_ops.py\", line 102, in <lambda>\n",
      "    (lambda w: w.sample(**random_action_kwargs))\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 680, in sample\n",
      "    batches = [self.input_reader.next()]\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 91, in next\n",
      "    batches = [self.get_data()]\n",
      "               ^^^^^^^^^^^^^^^\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 273, in get_data\n",
      "    item = next(self._env_runner)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 392, in _env_runner\n",
      "    active_envs, to_eval, outputs = _process_observations(\n",
      "                                    ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 627, in _process_observations\n",
      "    prep_obs = preprocessor.transform(raw_obs)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/models/preprocessors.py\", line 324, in transform\n",
      "    self.check_shape(observation)\n",
      "  File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/models/preprocessors.py\", line 71, in check_shape\n",
      "    raise ValueError(\n",
      "ValueError: Observation ({'energy': array(-27.596018, dtype=float32), 'comfort': array(-2.596018, dtype=float32), 'power': array(0., dtype=float32)} dtype=None) outside given space (Dict('comfort': Box(-1.0, 1.0, (), float32), 'energy': Box(-1.0, 1.0, (), float32), 'power': Box(-1.0, 1.0, (), float32)))!\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m 2025-02-01 09:37:39,591\tERROR actor_manager.py:804 -- Ray error (\u001b[36mray::RolloutWorker.apply()\u001b[39m (pid=72607, ip=192.168.200.249, actor_id=61eba594d5a0f1955ab56a9101000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7fa953e26290>)\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/utils/actor_manager.py\", line 194, in apply\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     raise e\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/utils/actor_manager.py\", line 183, in apply\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     return func(self, *args, **kwargs)\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/execution/rollout_ops.py\", line 102, in <lambda>\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     (lambda w: w.sample(**random_action_kwargs))\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 680, in sample\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     batches = [self.input_reader.next()]\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m                ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 91, in next\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     batches = [self.get_data()]\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m                ^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 273, in get_data\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     item = next(self._env_runner)\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 392, in _env_runner\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     active_envs, to_eval, outputs = _process_observations(\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m                                     ^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 627, in _process_observations\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     prep_obs = preprocessor.transform(raw_obs)\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/models/preprocessors.py\", line 324, in transform\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     self.check_shape(observation)\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/models/preprocessors.py\", line 71, in check_shape\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     raise ValueError(\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m ValueError: Observation ({'energy': array(-27.596018, dtype=float32), 'comfort': array(-2.596018, dtype=float32), 'power': array(0., dtype=float32)} dtype=None) outside given space (Dict('comfort': Box(-1.0, 1.0, (), float32), 'energy': Box(-1.0, 1.0, (), float32), 'power': Box(-1.0, 1.0, (), float32)))!), taking actor 1 out of service.\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m 2025-02-01 09:37:39,592\tERROR actor_manager.py:804 -- Ray error (\u001b[36mray::RolloutWorker.apply()\u001b[39m (pid=72608, ip=192.168.200.249, actor_id=7ee3c973eaa4b36c1e65cbc401000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7f77624b2f90>)\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/utils/actor_manager.py\", line 194, in apply\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     raise e\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/utils/actor_manager.py\", line 183, in apply\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     return func(self, *args, **kwargs)\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/execution/rollout_ops.py\", line 102, in <lambda>\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     (lambda w: w.sample(**random_action_kwargs))\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 680, in sample\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     batches = [self.input_reader.next()]\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m                ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 91, in next\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     batches = [self.get_data()]\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m                ^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 273, in get_data\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     item = next(self._env_runner)\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 392, in _env_runner\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     active_envs, to_eval, outputs = _process_observations(\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m                                     ^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 627, in _process_observations\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     prep_obs = preprocessor.transform(raw_obs)\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/models/preprocessors.py\", line 324, in transform\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     self.check_shape(observation)\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/models/preprocessors.py\", line 71, in check_shape\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     raise ValueError(\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m ValueError: Observation ({'energy': array(-27.64341, dtype=float32), 'comfort': array(-2.6434097, dtype=float32), 'power': array(0., dtype=float32)} dtype=None) outside given space (Dict('comfort': Box(-1.0, 1.0, (), float32), 'energy': Box(-1.0, 1.0, (), float32), 'power': Box(-1.0, 1.0, (), float32)))!), taking actor 2 out of service.\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m 2025-02-01 09:37:39,592\tERROR actor_manager.py:804 -- Ray error (\u001b[36mray::RolloutWorker.apply()\u001b[39m (pid=72609, ip=192.168.200.249, actor_id=e9820d63d13b1b370330fec001000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7fedf8f76590>)\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/utils/actor_manager.py\", line 194, in apply\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     raise e\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/utils/actor_manager.py\", line 183, in apply\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     return func(self, *args, **kwargs)\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/execution/rollout_ops.py\", line 102, in <lambda>\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     (lambda w: w.sample(**random_action_kwargs))\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 680, in sample\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     batches = [self.input_reader.next()]\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m                ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 91, in next\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     batches = [self.get_data()]\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m                ^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 273, in get_data\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     item = next(self._env_runner)\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 392, in _env_runner\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     active_envs, to_eval, outputs = _process_observations(\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m                                     ^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 627, in _process_observations\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     prep_obs = preprocessor.transform(raw_obs)\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/models/preprocessors.py\", line 324, in transform\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     self.check_shape(observation)\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/models/preprocessors.py\", line 71, in check_shape\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     raise ValueError(\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m ValueError: Observation ({'energy': array(-27.596018, dtype=float32), 'comfort': array(-2.596018, dtype=float32), 'power': array(0., dtype=float32)} dtype=None) outside given space (Dict('comfort': Box(-1.0, 1.0, (), float32), 'energy': Box(-1.0, 1.0, (), float32), 'power': Box(-1.0, 1.0, (), float32)))!), taking actor 3 out of service.\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m 2025-02-01 09:37:39,592\tERROR actor_manager.py:804 -- Ray error (\u001b[36mray::RolloutWorker.apply()\u001b[39m (pid=72610, ip=192.168.200.249, actor_id=edb47fdce7e6de7680050b0d01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7ff9d2085090>)\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/utils/actor_manager.py\", line 194, in apply\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     raise e\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/utils/actor_manager.py\", line 183, in apply\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     return func(self, *args, **kwargs)\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/execution/rollout_ops.py\", line 102, in <lambda>\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     (lambda w: w.sample(**random_action_kwargs))\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 680, in sample\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     batches = [self.input_reader.next()]\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m                ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 91, in next\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     batches = [self.get_data()]\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m                ^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 273, in get_data\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     item = next(self._env_runner)\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 392, in _env_runner\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     active_envs, to_eval, outputs = _process_observations(\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m                                     ^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/sampler.py\", line 627, in _process_observations\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     prep_obs = preprocessor.transform(raw_obs)\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/models/preprocessors.py\", line 324, in transform\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     self.check_shape(observation)\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m   File \"/home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/rllib/models/preprocessors.py\", line 71, in check_shape\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m     raise ValueError(\n",
      "\u001b[36m(PPO pid=72538)\u001b[0m ValueError: Observation ({'energy': array(-27.64341, dtype=float32), 'power': array(0., dtype=float32), 'comfort': array(-2.6434097, dtype=float32)} dtype=None) outside given space (Dict('comfort': Box(-1.0, 1.0, (), float32), 'energy': Box(-1.0, 1.0, (), float32), 'power': Box(-1.0, 1.0, (), float32)))!), taking actor 4 out of service.\n",
      "2025-02-01 09:37:40,829\tWARNING tune.py:219 -- Stop signal received (e.g. via SIGINT/Ctrl+C), ending Ray Tune run. This will try to checkpoint the experiment state one last time. Press CTRL+C (or send SIGINT/SIGKILL/SIGTERM) to skip. \n",
      "2025-02-01 09:37:40,848\tINFO tune.py:1009 -- Wrote the latest version of all result files and experiment state to '/home/AD/user/ray_results/PPO_2025-02-01_09-37-05' in 0.0180s.\n",
      "\u001b[36m(pid=72963)\u001b[0m WARNING: All log messages before absl::InitializeLog() is called are written to STDERR\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=72963)\u001b[0m E0000 00:00:1738402666.753684   72963 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=72963)\u001b[0m E0000 00:00:1738402666.757044   72963 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[36m(RolloutWorker pid=72610)\u001b[0m /usr/lib/python3.11/tempfile.py:1043: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/.energyplus_output_7f_26qi2'>\u001b[32m [repeated 6x across cluster]\u001b[0m\n",
      "\u001b[36m(RolloutWorker pid=72610)\u001b[0m   _warnings.warn(warn_message, ResourceWarning)\u001b[32m [repeated 6x across cluster]\u001b[0m\n",
      "\u001b[36m(RolloutWorker pid=72608)\u001b[0m /home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/controllables/energyplus/variables.py:396: RuntimeWarning: OutputVariable(OutputVariable.Ref(type='Zone Mean Air Temperature', key='0FGROUNDFLOOREAST1:OPENOFFICE')) requested while Kernel() is running; It may not be available until the next run. More info: https://energyplus.readthedocs.io/en/latest/datatransfer.html#datatransfer.DataExchange.request_variable\u001b[32m [repeated 24x across cluster]\u001b[0m\n",
      "\u001b[36m(RolloutWorker pid=72608)\u001b[0m   _warnings_.warn(\u001b[32m [repeated 24x across cluster]\u001b[0m\n",
      "2025-02-01 09:37:50,853\tERROR tune.py:1037 -- Trials did not complete: [PPO__TODO_MultiAgentBuildingEnv_1a129_00000, PPO__TODO_MultiAgentBuildingEnv_1a129_00001]\n",
      "2025-02-01 09:37:50,854\tINFO tune.py:1041 -- Total run time: 43.90 seconds (33.86 seconds for the tuning loop).\n",
      "2025-02-01 09:37:50,854\tWARNING tune.py:1056 -- Experiment has been interrupted, but the most recent state was saved.\n",
      "Resume experiment with: Tuner.restore(path=\"/home/AD/user/ray_results/PPO_2025-02-01_09-37-05\", trainable=...)\n",
      "2025-02-01 09:37:50,857\tWARNING experiment_analysis.py:180 -- Failed to fetch metrics for 2 trial(s):\n",
      "- PPO__TODO_MultiAgentBuildingEnv_1a129_00002: FileNotFoundError('Could not fetch metrics for PPO__TODO_MultiAgentBuildingEnv_1a129_00002: both result.json and progress.csv were not found at /home/AD/user/ray_results/PPO_2025-02-01_09-37-05/PPO__TODO_MultiAgentBuildingEnv_1a129_00002_2_2025-02-01_09-37-06')\n",
      "- PPO__TODO_MultiAgentBuildingEnv_1a129_00003: FileNotFoundError('Could not fetch metrics for PPO__TODO_MultiAgentBuildingEnv_1a129_00003: both result.json and progress.csv were not found at /home/AD/user/ray_results/PPO_2025-02-01_09-37-05/PPO__TODO_MultiAgentBuildingEnv_1a129_00003_3_2025-02-01_09-37-07')\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[36m(RolloutWorker pid=72965)\u001b[0m [2025-02-01 09:37:50,920 C 72965 72965] task_receiver.cc:185:  Check failed: _s.ok() Bad status: IOError: Broken pipe\n",
      "\u001b[36m(RolloutWorker pid=72965)\u001b[0m *** StackTrace Information ***\n",
      "\u001b[36m(RolloutWorker pid=72965)\u001b[0m /home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/_raylet.so(+0x1141c3a) [0x7f573b741c3a] ray::operator<<()\n",
      "\u001b[36m(RolloutWorker pid=72965)\u001b[0m /home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/_raylet.so(_ZN3ray6RayLogD1Ev+0x4d1) [0x7f573b7442c1] ray::RayLog::~RayLog()\n",
      "\u001b[36m(RolloutWorker pid=72965)\u001b[0m /home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/_raylet.so(+0x8e3576) [0x7f573aee3576] ray::core::TaskReceiver::HandleTask()::{lambda()#1}::operator()()\n",
      "\u001b[36m(RolloutWorker pid=72965)\u001b[0m /home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/_raylet.so(+0x8e3cfa) [0x7f573aee3cfa] std::_Function_handler<>::_M_invoke()\n",
      "\u001b[36m(RolloutWorker pid=72965)\u001b[0m /home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/_raylet.so(+0x9204ae) [0x7f573af204ae] ray::core::InboundRequest::Accept()\n",
      "\u001b[36m(RolloutWorker pid=72965)\u001b[0m /home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/_raylet.so(+0x90632f) [0x7f573af0632f] ray::core::NormalSchedulingQueue::ScheduleRequests()\n",
      "\u001b[36m(RolloutWorker pid=72965)\u001b[0m /home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/_raylet.so(+0xbe959c) [0x7f573b1e959c] EventTracker::RecordExecution()\n",
      "\u001b[36m(RolloutWorker pid=72965)\u001b[0m /home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/_raylet.so(+0xbe517e) [0x7f573b1e517e] std::_Function_handler<>::_M_invoke()\n",
      "\u001b[36m(RolloutWorker pid=72965)\u001b[0m /home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/_raylet.so(+0xbe55f6) [0x7f573b1e55f6] boost::asio::detail::completion_handler<>::do_complete()\n",
      "\u001b[36m(RolloutWorker pid=72965)\u001b[0m /home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/_raylet.so(+0x11b7bbb) [0x7f573b7b7bbb] boost::asio::detail::scheduler::do_run_one()\n",
      "\u001b[36m(RolloutWorker pid=72965)\u001b[0m /home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/_raylet.so(+0x11b9539) [0x7f573b7b9539] boost::asio::detail::scheduler::run()\n",
      "\u001b[36m(RolloutWorker pid=72965)\u001b[0m /home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/_raylet.so(+0x11b9c42) [0x7f573b7b9c42] boost::asio::io_context::run()\n",
      "\u001b[36m(RolloutWorker pid=72965)\u001b[0m /home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/_raylet.so(_ZN3ray4core10CoreWorker20RunTaskExecutionLoopEv+0xcd) [0x7f573ae0fffd] ray::core::CoreWorker::RunTaskExecutionLoop()\n",
      "\u001b[36m(RolloutWorker pid=72965)\u001b[0m /home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/_raylet.so(_ZN3ray4core21CoreWorkerProcessImpl26RunWorkerTaskExecutionLoopEv+0x85) [0x7f573aee73b5] ray::core::CoreWorkerProcessImpl::RunWorkerTaskExecutionLoop()\n",
      "\u001b[36m(RolloutWorker pid=72965)\u001b[0m /home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/_raylet.so(_ZN3ray4core17CoreWorkerProcess20RunTaskExecutionLoopEv+0x1d) [0x7f573aee75bd] ray::core::CoreWorkerProcess::RunTaskExecutionLoop()\n",
      "\u001b[36m(RolloutWorker pid=72965)\u001b[0m /home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/_raylet.so(+0x6b3267) [0x7f573acb3267] __pyx_pw_3ray_7_raylet_10CoreWorker_7run_task_loop()\n",
      "\u001b[36m(RolloutWorker pid=72965)\u001b[0m ray::RolloutWorker() [0x55dd30]\n",
      "\u001b[36m(RolloutWorker pid=72965)\u001b[0m ray::RolloutWorker(PyObject_Vectorcall+0x2c) [0x53b6ac] PyObject_Vectorcall\n",
      "\u001b[36m(RolloutWorker pid=72965)\u001b[0m ray::RolloutWorker(_PyEval_EvalFrameDefault+0x8f0) [0x52c2f0] _PyEval_EvalFrameDefault\n",
      "\u001b[36m(RolloutWorker pid=72965)\u001b[0m ray::RolloutWorker(PyEval_EvalCode+0xbb) [0x523fab] PyEval_EvalCode\n",
      "\u001b[36m(RolloutWorker pid=72965)\u001b[0m ray::RolloutWorker() [0x649bd7]\n",
      "\u001b[36m(RolloutWorker pid=72965)\u001b[0m ray::RolloutWorker() [0x64752f]\n",
      "\u001b[36m(RolloutWorker pid=72965)\u001b[0m ray::RolloutWorker() [0x6536e0]\n",
      "\u001b[36m(RolloutWorker pid=72965)\u001b[0m ray::RolloutWorker(_PyRun_SimpleFileObject+0x18b) [0x65342b] _PyRun_SimpleFileObject\n",
      "\u001b[36m(RolloutWorker pid=72965)\u001b[0m ray::RolloutWorker(_PyRun_AnyFileObject+0x44) [0x653254] _PyRun_AnyFileObject\n",
      "\u001b[36m(RolloutWorker pid=72965)\u001b[0m ray::RolloutWorker(Py_RunMain+0x20f) [0x651fdf] Py_RunMain\n",
      "\u001b[36m(RolloutWorker pid=72965)\u001b[0m ray::RolloutWorker(Py_BytesMain+0x27) [0x629917] Py_BytesMain\n",
      "\u001b[36m(RolloutWorker pid=72965)\u001b[0m /lib/x86_64-linux-gnu/libc.so.6(+0x2724a) [0x7f573c90524a]\n",
      "\u001b[36m(RolloutWorker pid=72965)\u001b[0m /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x85) [0x7f573c905305] __libc_start_main\n",
      "\u001b[36m(RolloutWorker pid=72965)\u001b[0m ray::RolloutWorker(_start+0x21) [0x6297b1] _start\n",
      "\u001b[36m(RolloutWorker pid=72965)\u001b[0m \n",
      "\u001b[36m(RolloutWorker pid=72963)\u001b[0m /home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/_raylet.so(+0x8e3576) [0x7efc76ce3576] ray::core::TaskReceiver::HandleTask()::{lambda()#1}::operator()()\n",
      "\u001b[36m(RolloutWorker pid=72963)\u001b[0m /home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/_raylet.so(+0x6b3267) [0x7efc76ab3267] __pyx_pw_3ray_7_raylet_10CoreWorker_7run_task_loop()\n",
      "\u001b[36m(RolloutWorker pid=72963)\u001b[0m /lib/x86_64-linux-gnu/libc.so.6(+0x2724a) [0x7efc7877624a]\n",
      "\u001b[36m(RolloutWorker pid=72963)\u001b[0m \n",
      "\u001b[36m(RolloutWorker pid=72964)\u001b[0m /home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/_raylet.so(+0x8e3576) [0x7f7c9f2e3576] ray::core::TaskReceiver::HandleTask()::{lambda()#1}::operator()()\n",
      "\u001b[36m(RolloutWorker pid=72964)\u001b[0m /home/AD/user/lab/bmstestbedc2f2/.venv/lib/python3.11/site-packages/ray/_raylet.so(+0x6b3267) [0x7f7c9f0b3267] __pyx_pw_3ray_7_raylet_10CoreWorker_7run_task_loop()\n",
      "\u001b[36m(RolloutWorker pid=72964)\u001b[0m /lib/x86_64-linux-gnu/libc.so.6(+0x2724a) [0x7f7ca0c1a24a]\n",
      "\u001b[36m(RolloutWorker pid=72964)\u001b[0m \n"
     ]
    }
   ],
   "source": [
    "from ray.tune.schedulers import PopulationBasedTraining\n",
    "from ray import tune, air\n",
    "from ray.rllib.policy.policy import PolicySpec\n",
    "from ray.rllib.algorithms.ppo import PPO, PPOConfig\n",
    "\n",
    "from bmstestbedc2f2.envs import _TODO_MultiAgentBuildingEnv\n",
    "from bmstestbedc2f2.utils import resolve_path\n",
    "\n",
    "\n",
    "pbt = PopulationBasedTraining(\n",
    "    time_attr=\"training_iteration\",\n",
    "    perturbation_interval=4,\n",
    "    resample_probability=0.25,\n",
    "    hyperparam_mutations={\n",
    "        \"lr\": tune.uniform(1e-5, 0.1),\n",
    "        \"batch_mode\": [\"complete_episodes\"],\n",
    "        \"train_batch_size\": [4000],\n",
    "        \"sgd_minibatch_size\": [32, 64, 128, 256, 512],\n",
    "        \"num_sgd_iter\": [10, 20, 30],\n",
    "        \"clip_param\": tune.uniform(0.1, 0.3),\n",
    "    },\n",
    ")\n",
    "\n",
    "tuner = tune.Tuner(\n",
    "    PPO,\n",
    "    param_space=(\n",
    "        _TODO_MultiAgentBuildingEnv.get_algo_config(\n",
    "            PPOConfig()\n",
    "            .api_stack(\n",
    "                enable_rl_module_and_learner=False,\n",
    "                enable_env_runner_and_connector_v2=False,\n",
    "            )\n",
    "            .rollouts(\n",
    "                sample_timeout_s=60,\n",
    "                num_env_runners=4, \n",
    "                rollout_fragment_length='auto',\n",
    "                # rollout_fragment_length=200,\n",
    "            )\n",
    "            .resources(num_gpus=1.),\n",
    "            env_config=dict(\n",
    "                bms_system='energyplus',\n",
    "            ),\n",
    "        )\n",
    "    ),\n",
    "    tune_config=tune.TuneConfig(\n",
    "        #reuse_actors=True,\n",
    "        scheduler=pbt,\n",
    "        num_samples=4,\n",
    "        metric=\"env_runners/episode_reward_mean\",\n",
    "        mode=\"max\",\n",
    "    ),\n",
    "    run_config=air.RunConfig(\n",
    "        stop={\"training_iteration\": 200},\n",
    "        checkpoint_config=air.CheckpointConfig(\n",
    "            checkpoint_at_end=True\n",
    "        ),\n",
    "        verbose=2,\n",
    "    )\n",
    ")\n",
    "results = tuner.fit()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/usr/lib/python3.11/ast.py:50: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2025-01-22_16-38-22_357299_58441/artifacts/2025-01-22_16-38-23/PPO_2025-01-22_16-38-22/driver_artifacts/PPO_MultiAgentBuildingEnv_4bfe2_00000_0_2025-01-22_16-38-23/result.json' mode='at' encoding='UTF-8'>\n",
      "  return compile(source, filename, mode, flags,\n",
      "ResourceWarning: Enable tracemalloc to get the object allocation traceback\n",
      "/usr/lib/python3.11/ast.py:50: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/ray/session_2025-01-22_16-38-22_357299_58441/artifacts/2025-01-22_16-38-23/PPO_2025-01-22_16-38-22/driver_artifacts/PPO_MultiAgentBuildingEnv_4bfe2_00000_0_2025-01-22_16-38-23/progress.csv' mode='at' encoding='UTF-8'>\n",
      "  return compile(source, filename, mode, flags,\n",
      "ResourceWarning: Enable tracemalloc to get the object allocation traceback\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "'NoneType' object has no attribute 'to_directory'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[2], line 2\u001b[0m\n\u001b[1;32m      1\u001b[0m best_result \u001b[38;5;241m=\u001b[39m results\u001b[38;5;241m.\u001b[39mget_best_result()\n\u001b[0;32m----> 2\u001b[0m \u001b[43mbest_result\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mcheckpoint\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mto_directory\u001b[49m(resolve_path(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124malgo_checkpoint\u001b[39m\u001b[38;5;124m'\u001b[39m))\n\u001b[1;32m      3\u001b[0m best_result\n",
      "\u001b[0;31mAttributeError\u001b[0m: 'NoneType' object has no attribute 'to_directory'"
     ]
    }
   ],
   "source": [
    "best_result = results.get_best_result()\n",
    "best_result.checkpoint.to_directory(resolve_path('algo_checkpoint'))\n",
    "best_result"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
